-- ============================================================================
-- LogLens — Bronze layer schema (ADR-001, ADR-002, ADR-003)
-- ============================================================================
-- The bronze layer is ELT, not ETL: entries are loaded with MINIMAL
-- transformation so ingestion almost never fails. The only processing at this
-- stage is computing a hash of the raw entry (for idempotency). All real
-- shaping — parsing into columns, UTC/severity normalization, PII policy —
-- happens later, moving bronze -> silver. Keeping bronze a near-verbatim load
-- means a malformed entry still lands (and can be inspected / reprocessed)
-- rather than crashing the pipeline.
--
-- Surrogate keys are UUIDs generated by the APPLICATION (Python), not the
-- database (ADR-014) — this keeps the design backend-agnostic (e.g. a future
-- SQLite path) and lets stateless nodes mint ids without a round-trip.
--
-- Idempotency (ADR-003): an entry's hash is unique WITHIN a file identity, not
-- globally, so rotated-log boundary duplication does not wrongly drop
-- legitimate repeated lines.
--
-- This script is safe to run repeatedly (IF NOT EXISTS everywhere).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Control table: one row per processed file.
-- Tracks what has been seen, its lifecycle status, and reprocessing history.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bronze_processed_logs (
    id              UUID PRIMARY KEY,          -- app-generated (uuid4)
    source_id       TEXT        NOT NULL,      -- which configured source
    log_type        TEXT        NOT NULL,      -- selects the parser (e.g. windows_service)
    file_name       TEXT        NOT NULL,      -- originating file name
    file_path       TEXT        NOT NULL,      -- shared location / directory
    file_hash       TEXT,                      -- detects whether the file changed
    status          TEXT        NOT NULL
                    DEFAULT 'in_progress'
                    CHECK (status IN ('in_progress', 'completed', 'failed')),
    reprocess_count INTEGER     NOT NULL DEFAULT 0,   -- times this file was re-run
    first_seen_utc  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at_utc  TIMESTAMPTZ NOT NULL DEFAULT now(),  -- last status change
    completed_utc   TIMESTAMPTZ,               -- when it reached 'completed'

    -- A file is identified by source + name + path; the same file is tracked once.
    CONSTRAINT uq_processed_file UNIQUE (source_id, file_name, file_path)
);

CREATE INDEX IF NOT EXISTS ix_processed_status
    ON bronze_processed_logs (status);

-- ----------------------------------------------------------------------------
-- Landing table: in-flight entries, one row per raw log entry.
-- Minimal transform — raw_entry is stored verbatim. The entry_hash is computed
-- over the raw entry exactly as received (ADR-003).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bronze_landing (
    id               UUID PRIMARY KEY,         -- app-generated (uuid4)
    processed_log_id UUID        NOT NULL
                     REFERENCES bronze_processed_logs (id) ON DELETE CASCADE,
    entry_hash       TEXT        NOT NULL,      -- dedup / idempotency key
    raw_entry        TEXT        NOT NULL,      -- the full raw entry, verbatim
    header_excerpt   TEXT,                      -- optional, nullable
    is_digested      BOOLEAN     NOT NULL DEFAULT FALSE,  -- promoted to silver?
    landed_at_utc    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Idempotency: a given entry hash appears at most once per file (ADR-003).
    CONSTRAINT uq_landing_entry UNIQUE (processed_log_id, entry_hash)
);

CREATE INDEX IF NOT EXISTS ix_landing_undigested
    ON bronze_landing (processed_log_id)
    WHERE is_digested = FALSE;

-- ----------------------------------------------------------------------------
-- Archive table: entries whose file has been fully digested (completed).
-- Same shape as landing; provides traceability for audit (ADR-002).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bronze_archive (
    id               UUID PRIMARY KEY,
    processed_log_id UUID        NOT NULL
                     REFERENCES bronze_processed_logs (id) ON DELETE CASCADE,
    entry_hash       TEXT        NOT NULL,
    raw_entry        TEXT        NOT NULL,
    header_excerpt   TEXT,
    is_digested      BOOLEAN     NOT NULL DEFAULT TRUE,
    landed_at_utc    TIMESTAMPTZ NOT NULL,
    archived_at_utc  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_archive_entry UNIQUE (processed_log_id, entry_hash)
);
